name: Android_IOS-CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Change flutter channel to master, enable macos support
        run: |
          flutter channel master
          flutter upgrade
          flutter pub get

      - name: Build apk, ios(simulator)
        run: |
          flutter build apk
          flutter build ios --debug --no-codesign --simulator

      - name: Debug
        run: |
          sudo npm install tree-node-cli -g
          treee build

      - name: Prepare release files
        run: |
          cp -r build/ios/Debug-iphonesimulator/Runner.app python_exercise_builder-ios-${{ steps.branch_name.outputs.SOURCE_NAME }}.app
          zip python_exercise_builder-ios-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r python_exercise_builder-ios-${{ steps.branch_name.outputs.SOURCE_NAME }}.app
          cp build/app/outputs/apk/release/app-release.apk python_exercise_builder-android-${{ steps.branch_name.outputs.SOURCE_NAME }}.apk
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: python_exercise_builder-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
