name: Linux-CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Change flutter channel to master, enable linux support
        run: |
          flutter channel master
          flutter upgrade
          flutter config --enable-linux-desktop
          flutter pub get

      - name: Patch for linux build
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor

      - name: Build linux
        run: |
          flutter build linux

      - name: Debug
        run: |
          sudo npm install tree-node-cli -g
          treee build

      - name: Prepare release files
        run: |
          cp -r build/linux/release python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}
          zip python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}.zip -r python_exercise_builder-linux-${{ steps.branch_name.outputs.SOURCE_NAME }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: python_exercise_builder-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true